[package]
name = "scoped-heed"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heed = { version = ">=0.20, <0.23", default-features = false, features = ["serde-bincode"] }
serde = { version = "1.0", features = ["derive", "alloc", "std"] }
bincode = "1.3"

[[example]]
name = "basic_usage"

[[example]]
name = "bytes_optimization"

[[example]]
name = "pure_bytes"

[dev-dependencies]
tempfile = "3"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "key_encoding_benchmark"
harness = false